### ISSUE TITLE
Getting error. 

### ISSUE THREAD

**Issue by muzammil-triffort** [CreateThrive/react-firebase-admin#159]
After setup everything. I can see the login page on screen but after login, I am getting this error:

`Unhandled Rejection (Error): Objects are not valid as a React child (found: Error: permission_denied at /users/1DfacH2cHqSUaxuQXO2QNvWeWII3: Client doesn't have permission to access the desired data.). If you meant to render a collection of children, use an array instead.
    in p (at Login/index.jsx:196)
    in form (at Login/index.jsx:122)
    in div (at Login/index.jsx:121)
    in div (at Login/index.jsx:110)
    in div (at Login/index.jsx:109)
    in div (at Login/index.jsx:108)
    in div (at Login/index.jsx:107)
    in div (at Login/index.jsx:106)
    in section (at Login/index.jsx:104)
    in Login (created by Context.Consumer)
    in Route (at Router/index.js:20)
    in Switch (at Router/index.js:19)
    in Router (created by BrowserRouter)
    in BrowserRouter (at Router/index.js:18)
    in RouterComponent (at src/index.js:32)
    in PersistGate (at src/index.js:21)
    in IntlProvider (at LanguageWrapper/index.js:24)
    in LanguageWrapper (at src/index.js:20)
    in Provider (at src/index.js:19)`

**Comment by MateoKruk** [comment]
Looks like an error related to the real time database rules. Are you sure the rules are deployed?

**Comment by muzammil-triffort** [comment]
Okay thank you. After updating the database read write rules now I can login inside dashboard. But not able to add new user from User's dashboard. I have already given the write access. Getting error like: 

`Unknown error, get in touch with your administrator`

**Comment by MateoKruk** [comment]
Can you show the rules that you've deployed to Firebase?

**Comment by MateoKruk** [comment]
I'll close this ticket. Feel free to contact us again!
