### ISSUE TITLE
Firebase init fails

### ISSUE THREAD

**Issue by pnogier** [CreateThrive/react-firebase-admin#221]
Hi guys,

I have a folder structured like this: 
/business
/customer
/admin (the react-firebase-admin cloned repository)
.firebaserc
firebase.json

I created those firebase files for hosting my customer and business apps, they use the same project,

When I try `firebase init` in my /admin directory, I get the error `.firebaserc already has a default project, using react-firebase-admin-eeac2.`

I want to keep those firebase files to continue handling my deploys in this way, what can I do ?

Thank you in advance,
Hope you guys can help me ❤️ 

- OS: MacOS BigSur

**Comment by MateoKruk** [comment]
Hey!

Thanks for reaching out. If you check your `admin` folder you should've already the `.firebaserc` created. Try deleting the file and run the command `firebase init` again.
