### ISSUE TITLE
error when running setup-admin-dashboard

### ISSUE THREAD

**Issue by affluent-bilby-classifieds** [CreateThrive/react-firebase-admin#60]
**Describe the bug**
I am getting the error "Error: No project active, but project aliases are available" at the part of the setup instructions that says to type in: npm run setup-admin-dashboard (Setting up the React frontend)
when I type in "npm -v" I get:
6.14.5

and 
"node -v"
v14.4.0

`npm run setup-admin-dashboard

> react-firebase-admin@0.1.0 setup-admin-dashboard /home/chris/my-app/react-firebase-admin/react-firebase-admin
> npm install && npm build && firebase deploy

> husky@4.2.5 install /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/husky
> node husky install

husky > Setting up git hooks
husky > Done

> node-sass@4.14.1 install /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/node-sass
> node scripts/install.js

Cached binary found at /home/chris/.npm/node-sass/4.14.1/linux-x64-83_binding.node

> @scarf/scarf@1.0.5 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/@scarf/scarf
> node ./report.js

> core-js@2.6.11 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

> core-js@3.6.5 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

> core-js-pure@3.6.5 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

> protobufjs@6.9.0 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/protobufjs
> node scripts/postinstall

> husky@4.2.5 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/husky
> opencollective-postinstall || exit 0

Thank you for using husky!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/husky/donate

> node-sass@4.14.1 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/node-sass
> node scripts/build.js

Binary found at /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/node-sass/vendor/linux-x64-83/binding.node
Testing binary
Binary is fine

> react-table@7.1.0 postinstall /home/chris/my-app/react-firebase-admin/react-firebase-admin/node_modules/react-table
> node ./scripts/postinstall.js || exit 0

👩‍💻 Use react-table at work?
🎉 Consider sponsoring/supporting its development at:
  
  https://github.com/sponsors/tannerlinsley

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-haste-map/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 2024 packages from 978 contributors and audited 2037 packages in 104.794s

81 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?

Error: No project active, but project aliases are available.

Run firebase use <alias> with one of these options:

  production (react-firebase-admin-eeac2)
  staging (react-firebase-admin-eeac2)
  default (react-firebase-admin-eeac2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-firebase-admin@0.1.0 setup-admin-dashboard: `npm install && npm build && firebase deploy`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-firebase-admin@0.1.0 setup-admin-dashboard script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/chris/.npm/_logs/2020-06-17T12_12_38_970Z-debug.log
chris@reactcore:~/my-app/react-firebase-admin/react-firebase-admin$ `

**To Reproduce**
too many to list

**Expected behavior**
expected it to build but I know this almost never happens the first try

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 20.04

**Smartphone (please complete the following information):**

**Additional context**
Any assistance is much appreciated. If I end up fixing it myself I will post what I did and close the ticket.

**Comment by MateoKruk** [comment]
Have you created a Firebase project and linked it with your local project? 

If not, you can do it with the following commands:
```
firebase loging
firebase init
```
After entering the init command you can follow these instructions: [link](https://github.com/CreateThrive/react-firebase-admin#getting-started)

**Comment by affluent-bilby-classifieds** [comment]
Hi Mateo, 

Thanks for reply so promptly.

I did go through those steps. I admit I did change my password halfway through as I realized I misunderstood part of the instructions and entered my gmail password as the dashboard admin password. I have "entered firebase logout" and then "firebase login" now.
I will run firebase init again and then setup-admin-dashboard to see if I get a different result.

**Comment by tpiaggio** [comment]
> 
> This time firebase init failed with: Error: Failed to get Firebase project react-firebase-admin-eeac2. Please make sure the project exists and your account has permission to access it.
> 

Please be sure to change the content of `.firebaserc`. The name of the project you see in the error message is the example project we use for this repo, you need to change the content and use your own project name

**Comment by MateoKruk** [comment]
Definitely, let's start with a fresh copy of the project. To be sure you can connect your local project with Firebase delete the following file from the root folder: `.firebaserc`.

With that done you can follow the quick start guide.

**Comment by affluent-bilby-classifieds** [comment]
Thanks Mateo and tpiaggio, I think you have nailed it. 

cat .firebaserc 
{
  "projects": {
    "production": "react-firebase-admin-eeac2",
    "staging": "react-firebase-admin-eeac2",
    "default": "react-firebase-admin-eeac2"
  }
}

Which is exactly what it is complaining about in the error I posted.

I will close the ticket. Thank you for your excellent assistance.
