### ISSUE TITLE
Cant run npm run setup-firebase

### ISSUE THREAD

**Issue by Yazington** [CreateThrive/react-firebase-admin#89]
**Describe the bug**
it says that it doesnt find the script to run it

**To Reproduce**
I just followed the readme and im getting the error

**Expected behavior**
like the readme would say to enter a certain path after

**Screenshots**
![image](https://user-images.githubusercontent.com/33079514/86728504-827a3e00-bffa-11ea-8bfc-90c72575c377.png)
![image](https://user-images.githubusercontent.com/33079514/86728713-ad649200-bffa-11ea-8dc2-75233ce041cd.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MateoKruk** [comment]
Can you show the full content of the debug file npm generated after this error? Did you run `npm install` before runing that script?

**Comment by Yazington** [comment]
@MateoKruk I did use npm install before and here is the full debug
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\darkb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'setup-firebase'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.2
4 verbose stack Error: missing script: setup-firebase
4 verbose stack     at run (C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:155:19)
4 verbose stack     at C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\lib\run-script.js:63:5
4 verbose stack     at C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:116:5
4 verbose stack     at C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:436:5
4 verbose stack     at checkBinReferences_ (C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:391:45)
4 verbose stack     at final (C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:434:3)
4 verbose stack     at then (C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:161:5)
4 verbose stack     at ReadFileContext.<anonymous> (C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\read-package-json\read-json.js:350:20)
4 verbose stack     at ReadFileContext.callback (C:\Users\darkb\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\graceful-fs.js:123:16)
4 verbose stack     at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:257:13)
5 verbose cwd C:\Users\darkb\Desktop\TRU-POS-master\functions
6 verbose Windows_NT 10.0.19041
7 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\darkb\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "setup-firebase"
8 verbose node v12.18.2
9 verbose npm  v6.14.5
10 error missing script: setup-firebase
11 verbose exit [ 1, true ]
`

**Comment by Yazington** [comment]
@MateoKruk Im new to programming, is the script setup-firebase made by you ? and if so how is it made?

**Comment by Yazington** [comment]
@MateoKruk I finally found the issue. Firebase init changed some of the files you had originally, so i took your original files on github and replaced them ( all of them )

**Comment by MateoKruk** [comment]
Good news! So you can have context the script `setup-firebase` runs the following command: `node setupProject.js`. The `setupProject.js` file is a little script that creates the DB on your Firebase account :).

**Comment by Yazington** [comment]
Thank you so much! How did you guys do this project, did you have react experience before?

**Comment by MateoKruk** [comment]
Pretty much it was my first real React project! @tpiaggio is a experienced developer and with his help it was much easier to build the project. 

But all in all React and Firebase are great beginner friendly technologies to build awesome projects. If you want some guidance don't hesitate to ask and I can show you some awesome online courses :).
